version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: auth_mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: auth_system
      MYSQL_USER: authuser
      MYSQL_PASSWORD: authpass123
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 10s
    networks:
      - auth_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: auth_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword123
    depends_on:
      - mysql
    networks:
      - auth_network

volumes:
  mysql_data:
    driver: local

networks:
  auth_network:
    driver: bridge
